/****************************************************************************
 * Riivolution support for USB Loader GX
 *
 * The on-demand boot sequence: reserve, place, install.
 *
 * Two things have to live in memory the booting game will not allocate over:
 * the redirect table, and the module that reads it. Both come out of one
 * reservation taken off the top of the game's MEM2 arena, because taking two
 * separate ones would mean lowering the arena boundary twice and getting the
 * second one wrong is silent - the game simply allocates over the first.
 *
 * The layout inside that reservation is fixed and checked here rather than
 * assumed:
 *
 *   newArenaHi -> [ module: code + bss ][ table ] <- old arena high
 *
 * The module goes first because it must be 32-byte aligned for the buffers
 * the storage engines DMA into, and the reservation itself is cache-line
 * aligned; the table only needs to be somewhere the module can read.
 *
 * The arithmetic is separated from the install so it can be host-tested. The
 * install itself writes to IOS and to low memory and is target-only.
 ***************************************************************************/
#ifndef RIIVO_ON_DEMAND_HPP_
#define RIIVO_ON_DEMAND_HPP_

#include <gctypes.h>
#include <string>
#include <vector>
#include "RiivoMem2Reserve.hpp"

namespace Riivo
{
	//! Where everything ends up. Produced without touching memory.
	struct OnDemandLayout
	{
		bool ok;
		u32 moduleAddr;   //!< module base, cache-line aligned
		u32 tableAddr;    //!< the redirect table
		u32 tableLen;
		u32 genAddr;      //!< staged ORIGINAL-slice store (0 when none)
		u32 genLen;       //!< bytes reserved at genAddr
		u32 newArenaHi;   //!< what MEM2 arena high must become
		u32 reserved;     //!< total taken from the game
		u32 heapLeft;
		std::string why;

		OnDemandLayout()
			: ok(false), moduleAddr(0), tableAddr(0), tableLen(0),
			  genAddr(0), genLen(0), newArenaHi(0), reserved(0), heapLeft(0) {}
	};

	//! Decide the layout for a table of `tableLen` bytes plus the module,
	//! with `genLen` staged-slice bytes after the table, given the game's
	//! MEM2 arena. Refuses rather than overlapping anything.
	bool PlanOnDemand(const Mem2Arena &arena, u32 tableLen,
					  OnDemandLayout &out, u32 genLen = 0);

	//! What the staged table is and what bounds it. `site` is a patch site
	//! the probe found. `partLba` is the FAT partition the table's paths
	//! are relative to.
	struct OnDemandMeta
	{
		u32 kind;       //!< 0 = whole-file table, 1 = RIV1 manifest
		u32 genBase;    //!< staged generated bytes, PPC view (0 when none)
		u32 genSize;    //!< bytes available at genBase
		u64 declSize;   //!< declared virtual-disc bytes (anti-shadow bound)
		u32 discId;     //!< game id the table was staged for
		u32 partIdx;    //!< partition index the table was staged for
		u32 epoch;      //!< PPC boot generation the ARM ack must echo

		OnDemandMeta()
			: kind(0), genBase(0), genSize(0), declSize(0), discId(0),
			  partIdx(0), epoch(0) {}
	};

	//! Carry out the layout: lower the arena, copy the table, install the
	//! module and point the hook at it. Target only. Returns false with
	//! `why` set and nothing changed, except that the arena may already
	//! have been lowered - which costs the game a little MEM2 and is
	//! otherwise harmless.
	//!
	//! `meta` selects which table the module serves and bounds it: kind 0
	//! is the whole-file redirect table (all existing behavior), kind 1 is
	//! the RIV1 manifest served by the segment reader with the declared
	//! size as its anti-shadow bound and the staged game/partition identity
	//! it must match. The ORIGINAL-slice store travels in the same
	//! reservation after the table (`genLen` below); an empty store with
	//! GENERATED extents refuses at module init, never serves partial.
	bool InstallOnDemand(u32 site, const std::vector<u8> &table, u32 partLba,
						 const OnDemandMeta &meta,
						 OnDemandLayout &layout, std::string &why,
						 u32 genLen = 0);
}

#endif
