/****************************************************************************
 * Riivolution support for USB Loader GX
 *
 * The on-demand module's compiled bytes, and the handful of offsets the loader
 * needs to place them. Generated by source/riivo/ios/genblob.py from the C in
 * source/riivo/ios; see RiivoModuleBlob.cpp.
 ***************************************************************************/
#ifndef RIIVO_MODULE_BLOB_HPP_
#define RIIVO_MODULE_BLOB_HPP_

#include <gctypes.h>

namespace Riivo
{
	//! Where the blob was linked. Every absolute word in it is relative to
	//! this, and is fixed up against wherever it actually lands.
	extern const u32 RIIVO_MODULE_LINK_BASE;

	//! Bytes to copy (text + data). BSS carries none and is cleared instead -
	//! the module's statics must start zero and nothing on the console does
	//! that for us.
	extern const u32 RIIVO_MODULE_CODE_LEN;
	extern const u32 RIIVO_MODULE_BSS_LEN;

	//! riivo_di_read, as an offset into the blob. Even: a Thumb symbol's bit 0
	//! is state, not address, and the BL encoding has no room for it.
	extern const u32 RIIVO_MODULE_ENTRY_OFF;

	//! g_params, the block the loader fills in before the hook goes live.
	extern const u32 RIIVO_MODULE_PARAMS_OFF;

	//! Byte offsets of the absolute words needing the load delta added.
	//! Only R_ARM_ABS32; pc-relative calls are left alone, and adding a delta
	//! to one would send an internal call somewhere arbitrary.
	extern const u32 RIIVO_MODULE_RELOC_NUM;
	extern const u32 RIIVO_MODULE_RELOCS[];

	extern const u8 RIIVO_MODULE_CODE[];
}

#endif
