/****************************************************************************
 * Riivolution support for USB Loader GX
 *
 * Versioned runtime manifest (Gate B contract, WP2-WP5 shared).
 *
 * Freezes the PPC loader -> IOS runtime interface before parallel
 * implementation. Little-endian, fixed-width fields; the ARM reader
 * assembles every field from bytes and never depends on struct layout.
 *
 * Extent model (arch 3.2): the patched partition is ordered, non-overlapping
 * extents. Gaps (Original) are delegated to the original cIOS reader and are
 * NOT listed; only diverted ranges appear here:
 *   External  - bytes come from an SD/USB/RiiFS file (path + source offset).
 *   Generated - bytes come from rebuilt metadata (FST) in reserved memory.
 *   Zero      - explicit padding/expansion bytes.
 * A read crossing extent boundaries must be split and reassembled by the
 * runtime; padding between placed files reads as zero.
 *
 * Relation to the existing table: RiivoRedirectTable ('RIIV') carries only
 * External extents by path. This manifest ('RIV1') is its versioned
 * successor and also describes Generated/Zero extents, provider limits, and
 * integrity. Both readers validate sorted/non-overlapping order at init.
 * Emitters must not pass loader-owned pointers; the table lives in reserved
 * MEM2 that survives game startup (RiivoMem2Reserve/RiivoOnDemand).
 *
 * Lifecycle: init (validate) -> activate (install hook) -> failure (refuse
 * the jump, never launch partial) -> cleanup (revert). Conditional
 * `original` mismatches keep their skip behavior in the memory stage.
 ***************************************************************************/
#ifndef RIIVO_MANIFEST_HPP_
#define RIIVO_MANIFEST_HPP_

#include <gctypes.h>
#include <string>
#include <vector>

namespace Riivo
{
	//! Magic 'RIV1' little-endian. Bump on any layout change so a stale
	//! runtime refuses instead of misreading.
	static const u32 RIIVO_MANIFEST_MAGIC = 0x31564952;
	static const u16 RIIVO_MANIFEST_VERSION = 1;

	//! Header layout (bytes, all LE). Total RIIVO_MANIFEST_HEADER.
	//!  +0  magic      u32
	//!  +4  version    u16
	//!  +6  headerLen  u16 (== RIIVO_MANIFEST_HEADER)
	//!  +8  totalSize  u32 (header + entries + blob)
	//!  +12 caps       u32 (capability flags, see below)
	//!  +16 crc32      u32 (over whole table with this field zeroed)
	//!  +20 count      u32 (extent entries)
	//!  +24 strOff     u32 (offset from table base to string blob)
	//!  +28 partLba    u32 (FAT partition LBA, or RIIVO_PART_DISCOVER)
	//!  +32 discId     u32 (first 4 bytes of game id, BE order as u32)
	//!  +36 partIdx    u32 (partition index within the disc)
	//!  +40 provCaps   u32 (provider limits/flags, see below)
	//!  +44 reserved   u32 (must be zero)
	static const u32 RIIVO_MANIFEST_HEADER = 48;

	//! Entry layout (bytes, all LE). Total RIIVO_MANIFEST_ENTRY.
	//!  +0  discOffLo  u32
	//!  +4  discOffHi  u32   (partition-byte offset of this extent)
	//!  +8  length     u32
	//!  +12 kind       u16   (RIIVO_EXT_* below)
	//!  +14 source     u16   (RIIVO_SRC_* below)
	//!  +16 srcOffLo   u32
	//!  +20 srcOffHi   u32   (byte offset within the source file/object)
	//!  +24 pathOff    u32   (blob offset of NUL-terminated path, External
	//!                       only; 0 otherwise)
	//!  +28 genOff     u32   (reserved-memory offset of generated bytes,
	//!                       Generated only; 0 otherwise)
	static const u32 RIIVO_MANIFEST_ENTRY = 32;

	//! Extent kinds.
	static const u16 RIIVO_EXT_EXTERNAL = 1;
	static const u16 RIIVO_EXT_GENERATED = 2;
	static const u16 RIIVO_EXT_ZERO = 3;

	//! Source identifiers (External only).
	static const u16 RIIVO_SRC_NONE = 0;
	static const u16 RIIVO_SRC_SD = 1;
	static const u16 RIIVO_SRC_USB = 2;
	static const u16 RIIVO_SRC_RIIFS = 3;

	//! Capability flags (caps).
	static const u32 RIIVO_CAP_SPLIT_READ = 1u << 0; // boundary-crossing split
	static const u32 RIIVO_CAP_ZERO_FILL = 1u << 1;  // Zero extents honored
	static const u32 RIIVO_CAP_GENERATED = 1u << 2;  // Generated extents honored

	//! Provider flags (provCaps): bounded caches, no per-read heap alloc.
	static const u32 RIIVO_PROV_BOUNDED = 1u << 0;

	//! Tells the runtime to discover the FAT partition via the MBR.
	//! Mirrors RIIVO_PART_DISCOVER in RiivoRedirectTable.hpp.
	static const u32 RIIVO_MANIFEST_DISCOVER = 0xFFFFFFFF;

	//! One diverted extent, loader-side view. `discOffset` is PartitionBytes.
	struct ManifestExtent
	{
		u64 discOffset;
		u32 length;
		u16 kind;
		u16 source;
		u64 srcOffset;
		std::string path; // External only, absolute within the partition
		u32 genOff;       // Generated only, offset in reserved memory

		ManifestExtent()
			: discOffset(0), length(0), kind(RIIVO_EXT_EXTERNAL),
			  source(RIIVO_SRC_NONE), srcOffset(0), genOff(0) {}
	};

	//! Serialised size without building. For MEM2 reservation sizing.
	u64 ManifestTableSize(const std::vector<ManifestExtent> &extents);

	//! Build a v1 manifest. Refuses (false + why) on unsorted/overlapping
	//! extents, bad paths, Zero with a path, External without an absolute
	//! path, or a table that would exceed a u32. Emits LE by hand; never by
	//! struct memcpy (PPC is big-endian).
	bool BuildManifestV1(const std::vector<ManifestExtent> &extents,
						 u32 partLba, u32 discId, u32 partIdx,
						 u32 caps, u32 provCaps,
						 std::vector<u8> &out, std::string &why);

	//! Validate a received table without touching hardware: magic, version,
	//! header length, total size, crc, count/strOff bounds, entry order and
	//! overlap, blob termination. False + why on any failure.
	bool ValidateManifestV1(const u8 *base, u32 len, std::string &why);
}

#endif
