"""Turn the linked ARM module into a C++ array the loader can carry.

The Wii build has no ARM compiler in it, so the module is built here, offline,
and its bytes are embedded. That is the same arrangement redirect.S already
has, and it has the same hazard: the embedded copy is the one that runs, so
nothing would notice if only the sources changed. test_moduleinstall checks the
embedded blob against a freshly linked one whenever devkitARM is present.

Relocations matter because the blob is copied to wherever the MEM2 reservation
landed, which is not known until the game is booting. R_ARM_ABS32 words hold
absolute addresses and need the load delta added; R_ARM_THM_CALL is
pc-relative and must be left alone - adding a delta to one would send an
internal call somewhere arbitrary.

Usage: python genblob.py <module.elf> <out.cpp>
"""
import struct
import subprocess
import sys
import os

READELF = os.environ.get("READELF",
                         r"C:/devkitPro/devkitARM/bin/arm-none-eabi-readelf")
OBJCOPY = os.environ.get("OBJCOPY",
                         r"C:/devkitPro/devkitARM/bin/arm-none-eabi-objcopy")
NM = os.environ.get("NM", r"C:/devkitPro/devkitARM/bin/arm-none-eabi-nm")


def run(*args):
    return subprocess.check_output(list(args)).decode("utf-8", "replace")


def main():
    if len(sys.argv) < 3:
        sys.exit(__doc__)
    elf, out = sys.argv[1], sys.argv[2]

    syms = {}
    for line in run(NM, elf).splitlines():
        parts = line.split()
        if len(parts) == 3:
            syms[parts[2]] = int(parts[0], 16)

    for need in ("riivo_di_read", "g_params", "__riivo_bss_start",
                 "__riivo_bss_end"):
        if need not in syms:
            sys.exit("missing symbol: %s" % need)

    base = syms["__riivo_bss_start"] & ~0xFFFFF  # link ORIGIN, 1 MB aligned
    copy_len = syms["__riivo_bss_start"] - base
    bss_len = syms["__riivo_bss_end"] - syms["__riivo_bss_start"]

    raw = elf + ".bin"
    run(OBJCOPY, "-O", "binary", "--only-section=.text",
        "--only-section=.data", elf, raw)
    with open(raw, "rb") as f:
        code = f.read()
    if len(code) != copy_len:
        sys.exit("binary is %d bytes, expected %d" % (len(code), copy_len))

    # Only relocations against sections that are actually loaded. The debug
    # sections carry their own, with section-relative offsets that look like
    # plausible addresses and silently produce garbage - the first version of
    # this took every line and emitted negative offsets.
    WANTED = (".rel.text", ".rel.data", ".rel.rodata")
    relocs = []
    skipped = {}
    section = None
    for line in run(READELF, "-r", elf).splitlines():
        if line.startswith("Relocation section"):
            name = line.split("'")[1] if "'" in line else ""
            section = name if name in WANTED else None
            continue
        if section is None:
            continue
        parts = line.split()
        if len(parts) < 3 or not parts[0].strip():
            continue
        try:
            where = int(parts[0], 16)
        except ValueError:
            continue
        kind = parts[2]
        if kind == "R_ARM_ABS32":
            off = where - base
            if off < 0 or off + 4 > copy_len:
                sys.exit("relocation at %08x is outside the copied bytes "
                         "(offset %d, blob is %d)" % (where, off, copy_len))
            relocs.append(off)
        else:
            skipped[kind] = skipped.get(kind, 0) + 1
    if not relocs:
        sys.exit("no relocations found - was the module linked --emit-relocs?")
    relocs.sort()

    with open(out, "w", newline="\n") as f:
        f.write("""/****************************************************************************
 * Riivolution support for USB Loader GX
 *
 * GENERATED by source/riivo/ios/genblob.py - do not edit by hand.
 *
 * The on-demand module, compiled for the Starlet: big-endian ARM, Thumb,
 * freestanding. The Wii build has no ARM compiler, so these bytes are built
 * offline and carried. test_moduleinstall re-links the sources and compares,
 * whenever devkitARM is available.
 ***************************************************************************/
#include "RiivoModuleBlob.hpp"

namespace Riivo
{
""")
        f.write("\tconst u32 RIIVO_MODULE_LINK_BASE = 0x%08Xu;\n" % base)
        f.write("\tconst u32 RIIVO_MODULE_CODE_LEN  = %uu;\n" % copy_len)
        f.write("\tconst u32 RIIVO_MODULE_BSS_LEN   = %uu;\n" % bss_len)
        f.write("\tconst u32 RIIVO_MODULE_ENTRY_OFF = 0x%Xu;\n"
                % (syms["riivo_di_read"] - base))
        f.write("\tconst u32 RIIVO_MODULE_PARAMS_OFF= 0x%Xu;\n"
                % (syms["g_params"] - base))
        f.write("\tconst u32 RIIVO_MODULE_RELOC_NUM = %uu;\n\n" % len(relocs))

        f.write("\tconst u8 RIIVO_MODULE_CODE[%u] = {\n" % len(code))
        for i in range(0, len(code), 16):
            row = ", ".join("0x%02X" % b for b in code[i:i + 16])
            f.write("\t\t%s,\n" % row)
        f.write("\t};\n\n")

        f.write("\tconst u32 RIIVO_MODULE_RELOCS[%u] = {\n" % len(relocs))
        for i in range(0, len(relocs), 8):
            row = ", ".join("0x%04X" % r for r in relocs[i:i + 8])
            f.write("\t\t%s,\n" % row)
        f.write("\t};\n}\n")

    print("%s: %u bytes code, %u bss, %u relocs (skipped %s)"
          % (out, copy_len, bss_len, len(relocs),
             ", ".join("%s x%d" % kv for kv in sorted(skipped.items())) or "none"))


if __name__ == "__main__":
    main()
