/* The module the loader injects: what the DI hook calls, and everything the
 * loader has to fill in before it does.
 *
 * The parameter block sits at a known offset in the blob so the loader can
 * find it without a symbol table - it is located by its magic, then written,
 * then the whole blob is verified by uncached read-back. Every address in it
 * is one that cannot be known until the console is running: where d2x's device
 * routines live, where the table was placed, which FAT partition to mount.
 *
 * Addresses in `dst` come from the PPC and are in the PPC's view of memory
 * (0x80xxxxxx for MEM1, 0x90xxxxxx for MEM2). Starlet sees the same memory at
 * 0x00xxxxxx and 0x10xxxxxx, so every one of them has to be masked before it
 * is written through. Getting that wrong is an ARM data abort inside an
 * unanswered IPC, which is a hard freeze with nothing on screen.
 */
#ifndef RIIVO_IOS_H
#define RIIVO_IOS_H

#include "riivo_glue.h"
#include "riivo_segread.h"
#include <stdint.h>

#define RIIVO_IOS_MAGIC   0x5249494Fu   /* 'RIIO' */

/* Table kinds the module serves. RIIV is the whole-file redirect table;
   RIV1 is the segmented manifest (external + source offset, zero,
   generated). Anything else refuses at init: serving a table whose
   format is unknown would be guessing. */
#define RIIVO_TABLE_RIIV  0
#define RIIVO_TABLE_RIV1  1

/* Paged RIV1: the table lives as a file on the mod volume (fixed paths
   below), paged through a resident index. Anything else refuses at init:
   serving a table whose format is unknown would be guessing. */
#define RIIVO_TABLE_PAGED 2

/* Table-file paths on the mod volume, shared with the PPC stager
   (RiivoManifest RIIVO_PAGED_*): byte-identical strings asserted host-side. */
#define RIIVO_PAGED_TABLE_FILE "/riivolution/rxivtbl.bin"
#define RIIVO_PAGED_GEN_FILE   "/riivolution/rxivgen.bin"

/* PPC 0x80xxxxxx -> 0x00xxxxxx, 0x90xxxxxx -> 0x10xxxxxx. */
#ifdef RIIVO_HOST_TEST
/* Host tests exercise only paths that never dereference a masked pointer
   (the unarmed gate returns first); the intermediate cast keeps LP64
   builds compiling with a warning instead of an error. Anything that
   dereferences through this macro stays ARM-only by construction. */
#define RIIVO_PHYS(a)     ((unsigned int)(uintptr_t)(a))
#else
#define RIIVO_PHYS(a)     ((unsigned int) (a) & 0x3FFFFFFFu)
#endif

/* Return codes from riivo_di_read. */
#define RIIVO_DI_OK      0
#define RIIVO_DI_MISS    1   /* not ours; the caller must fall through */
#define RIIVO_DI_FAIL   (-1)

typedef void (*riivo_sync_fn)(void *addr, unsigned int len);

typedef struct
{
	/* Line 0 (offsets 0-28): PPC-owned install inputs, written once with
	   the blob and flushed before the hook goes live. ARM only reads. */
	unsigned int magic;       /* RIIVO_IOS_MAGIC, so the loader can find this */
	unsigned int table;       /* redirect table, PPC address */
	unsigned int table_len;
	unsigned int part_lba;    /* FAT partition start, or RR_PART_DISCOVER */
	unsigned int read_a;      /* d2x (lba, count, buf) */
	unsigned int read_b;      /* d2x (0, lba, count, buf) */
	unsigned int config;      /* d2x device config; word +8 picks the above */
	unsigned int sync;        /* os_sync_after_write, or 0 */

	/* Line 1 (offsets 32-60): PPC-owned RIV1 inputs, same lifetime as
	   line 0. Ignored unless tableKind selects RIV1; every word is
	   checked at init before a single read is served. */
	unsigned int tableKind;   /* RIIVO_TABLE_RIIV or RIIVO_TABLE_RIV1 */
	unsigned int genBase;     /* staged generated bytes, PPC view (or 0) */
	unsigned int genSize;     /* bytes available at genBase */
	unsigned int declLo;      /* declared virtual-disc bytes, low word */
	unsigned int declHi;      /* declared virtual-disc bytes, high word */
	unsigned int expDiscId;   /* game id the table was staged for */
	unsigned int expPartIdx;  /* partition index the table was staged for */
	unsigned int epoch;       /* PPC boot generation; ARM echoes it to
								 acked when init completes under it */

	/* Line 2 (offsets 64-92): the activation word plus pad. The ONLY word
	   the PPC mutates post-install, flushed alone (32 bytes): ARM never
	   stores anywhere on this line, so invalidating it discards nothing,
	   and flushing it can clobber no ARM-written counter. */
	unsigned int armed;       /* 1 when the staged contract is complete:
								 the slice store (if any) is filled and
								 verified. While 0 every read MISSES without
								 initializing, so nothing can serve - or
								 cache - a half-staged table. The loader sets
								 it at install when no fill is pending and
								 late after a successful fill. */
	unsigned int _pad1[7];    /* zero; keeps counters on their own line */

	/* Line 3 (offsets 96-116): ARM-owned. Written by the module from its
	   first read on; the PPC reads these words through the uncached alias
	   only and must never flush this line after handoff (a writeback of
	   a PPC-dirty line would clobber ARM's counts). Never invalidated:
	   that would discard ARM's own dirty data. */
	unsigned int state;       /* 0 untried, 1 ready, else init error:
								   2 glue, 3 table, 4 mount, 5 rr, 6 sr,
								   7 kind, 8 gen cap, 9 paged open */
	unsigned int reads;       /* DI reads served */
	unsigned int misses;      /* DI reads that were not ours */
	unsigned int errors;
	unsigned int acked;       /* epoch ARM init completed under (0 = none) */
} riivo_ios_params;

extern riivo_ios_params g_params;

/* Mount the card and validate the table. Safe to call more than once; only
   the first call does anything. Returns RIIVO_DI_OK or RIIVO_DI_FAIL. */
int riivo_ios_init(void);

/* Serve one DI read. `off_words` is the disc offset in words, exactly as it
   arrives in the command block; `dst` is the PPC-side destination.
   Returns RIIVO_DI_MISS when the offset is outside the mod region, and the
   caller must then run the stock read path unchanged. */
int riivo_di_read(unsigned int off_words, unsigned int len, void *dst);

#endif
